katalog/vsphere-csi/vsphere-csi-controller-deployment.yaml

storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver

Change apiVersion for storage CSIDriver

---

roles/etcd/templates/kubeadm-etcd.yml.j2
roles/kube-control-plane/templates/kubeadm.yml.j2

Hi team, another change to make the kubeadm.yml files upgraded to the latest apiVersion v1beta2. 
These changes are already tested in a 1.22 on-premise cluster

[FEATURE] - Update kubeadm.yml files to v1beta2

---

roles/containerd/tasks/main.yml
roles/containerd/templates/config.toml.j2

Add a missing configuration option to choose systemd as the cgroups driver to be aligned with what we configure in kubeadm.
See:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd-systemd

fix(containerd): set cgroups driver to systemd

---

docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.21.14.md
katalog/vsphere-cm/README.md
roles/kube-node-common/defaults/main.yml
roles/kube-node-common/tasks/node.yml
roles/kube-node-common/tasks/repo-RedHat.yml
roles/kube-node-common/tasks/repo-Rocky.yml

This PR adds:
- lock and hold in RHEL/Debian systems on Kubernetes packages
- release note for 1.21.14
- update compatibility matrix
PS: i tested the install and upgrade procedure on ubuntu 20.04 and rocky 8

feat: adding hold and unhold / lock and unlock for kubernetes packages

---

.drone.yml
roles/kube-node-common/defaults/main.yml

Kubeadm changed the version of critools that it depends on from `1.25.0` to `1.26.0` starting from the package `kubeadm-1.25.6-00`, the previous patch releases of the kubeadm package depended on critools `1.25.0`.

Fix cri-tools ubuntu 1.25.6

---

.gitignore
README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.26.3.md
examples/playbooks/55.upgrade-control-plane.yml
katalog/vsphere-cm/README.md
katalog/vsphere-cm/vsphere-cloud-controller-manager.yaml
katalog/vsphere-csi/MAINTENANCE.md
katalog/vsphere-csi/README.md
katalog/vsphere-csi/vsphere-csi-driver.yaml
roles/containerd/defaults/main.yml
roles/containerd/tasks/main.yml
roles/etcd/defaults/main.yml
roles/kube-control-plane/defaults/main.yml
roles/kube-node-common/defaults/main.yml

- update Ansible Roles to suport Kubernetes 1.26.3
- update vSphere katalog to support Kubernetes 1.26
- bump etcd version in etcd role
- update docs and add release notes
Tested with:
```command
$ kubectl get nodes -o wide
NAME      STATUS   ROLES           AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
master1   Ready    control-plane   71m   v1.26.3   <reacted>        <none>        Ubuntu 22.04.2 LTS   5.15.0-71-generic   containerd://1.7.0
worker1   Ready    <none>          70m   v1.26.3   <reacted>        <none>        Ubuntu 22.04.2 LTS   5.15.0-71-generic   containerd://1.7.0
worker2   Ready    <none>          70m   v1.26.3   <reacted>        <none>        Ubuntu 22.04.2 LTS   5.15.0-71-generic   containerd://1.7.0
```

feat: add Kubernetes 1.26

---

README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.26.3.md
examples/playbooks/55.upgrade-control-plane.yml
katalog/vsphere-cm/README.md
katalog/vsphere-cm/vsphere-cloud-controller-manager.yaml
katalog/vsphere-csi/MAINTENANCE.md
katalog/vsphere-csi/README.md
katalog/vsphere-csi/vsphere-csi-driver.yaml
roles/containerd/defaults/main.yml
roles/containerd/tasks/main.yml
roles/etcd/defaults/main.yml
roles/kube-control-plane/defaults/main.yml
roles/kube-node-common/defaults/main.yml

* feat: add Kubernetes 1.26
- update Ansible Roles to suport Kubernetes 1.26.3
- update vSphere katalog to support Kubernetes 1.26
- bump etcd version in etcd role
- update docs and add release notes
* chore: remove gitignore tracking
* feat: cherrypick #50 - allow installing older versions
* fix(containerd): checksum for downloads
validate downloaded files using checksum and also with the checksum to trigger the download again when the version has changed
* feat(examples): add etcd upgrade
* chore(containerd): restore line formatting

feat: add Kubernetes 1.26 (#57)

---

roles/containerd/defaults/main.yml
roles/containerd/handlers/main.yml
roles/containerd/tasks/main.yml
roles/containerd/tasks/nvidia.yml
roles/containerd/templates/config.toml.j2
roles/containerd/vars/main.yml

This PR adds support to the Nvidia container toolkit in the `containerd` ansible role.
A new boolean variable `containerd_nvidia_enabled` (default = `false`) has been introduced. 
In case it's `true` the role will 
- install the package `nvidia-container-toolkit` using APT or YUM
- configure the `config.toml` properly

feat(containerd): add support to nvidia

---

roles/containerd/defaults/main.yml
roles/containerd/templates/config.toml.j2

Add a new `containerd_registry_configs` variable that allows to configure registry authentication, tls insecure connections and mirrors at containerd level.

feat(containerd): add registry_configs option

---

roles/kube-node-common/tasks/repo-Debian.yml

Reorder tasks for removing the deprecated Google repo before updating APT's cache.

fix(node-common): remove deprecated repo before updating cache

---

roles/containerd/defaults/main.yml
roles/containerd/tasks/main.yml
roles/etcd/tasks/install.yml

Autodetect node's architecture instead of harcoding it. This enables installing on arm64 architectures, for example.
> [!NOTE]
> The on-premises images in our registry are only synced for AMD64 architecture, so the master role will fail because the kube-apiserver, scheduler, etc. won't come up and kubeadm will exit.
>
> One workaround is installing multiarch support for containerd:
> ```shell
> wget https://github.com/containerd/nerdctl/releases/download/v1.7.4/nerdctl-1.7.4-linux-arm64.tar.gz
> tar xfz nerdctl*
> sudo ./nerdctl run --privileged --rm tonistiigi/binfmt --install all
> ```

feat(containerd, etcd): autodetect node architecture

---

roles/etcd/defaults/main.yml
roles/etcd/templates/etcd.env.j2

This PR allows overriding the etcd initial cluster state from `new` to `existing` in case an etcd node has been recovered or created later.
Ansible allow overriding this option for specific nodes in the `hosts` file. Here's an example using the yaml syntax:
```yaml filename=hosts.yaml
master:
hosts:
node01:
ansible_host: 10.0.0.1
node02:
ansible_host: 10.0.0.2
etcd_initial_cluster_state: "existing"
node03:
ansible_host: 10.0.03
```
> ⚠️ This is not a procedure to restore or join a new etcd node. This change avoid overriding the etcd settings and breaking a node

feat: possibility to override etcd initial cluster state 

---

roles/containerd/tasks/docker-remove.yml

I'm trying to deploy KFD on a set of new VMs, and our default Rocky 8 image is configured with Docker. The Ansible playbook will fail with:
```bash
"docker rm" requires at least 1 argument.
See 'docker rm --help'.
Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]
Remove one or more containers
```
That's because the output of `docker ps -a -q` is empty. I've fixed all three calls to go through `xargs -r` so it's not even trying when there is nothing to delete.

Do not error out when there are no Docker containers or images

---

roles/kube-control-plane/defaults/main.yml
roles/kube-control-plane/templates/kubeadm.yml.j2

Useful when accessing the cluster through a bastion.
In a context in which the API Server is accessible through a bastion, `kubernetes_apiserver_certSANs` can be used to set the IP address of the bastion as an alternative name in the API Server certificates.
The default value `kubernetes_api_SAN` has been removed since it wasn't used in the template for `kubeadm.yaml` file.

Configure api server alternative names

---

roles/containerd/defaults/main.yml
roles/containerd/templates/config.toml.j2

relax contianerd `registryConfigs` to allow setting registry mirrors without needing to set also authentication details.

feature(containerd): registry mirrors

---

examples/playbooks/98.cluster-certificates-renewal.yaml

As per title.
Tested locally with Kubernetes 1.26, 1.27, 1.28, 1.29.
Related to: [480](https://github.com/sighupio/product-management/issues/480)

feat: add playbook for cluster certificates renewal

---

examples/playbooks/56.upgrade-worker-nodes.yml
examples/playbooks/99.docker-replacement-with-containerd.yml
examples/playbooks/hosts.yaml
roles/kube-control-plane/files/kube.sh
roles/kube-control-plane/tasks/main.yml
roles/kube-control-plane/tasks/upgrade.yml

starting from kubernetes 1.29, kubeadm creates two kubeconfig files for administrators:
- admin.conf: this is a NEW user that has a rolebinding for the role kubeadm:cluster-admins and not masters as before.
- super-admin.conf: this is the equivalent to the admin.conf created in previous versions. It is a member of the system:masters group, so RBAC does not apply.
Now both are downloaded and we let the user choose which one to use.

fetch both admin.conf and superadmin.conf

---

roles/containerd/defaults/main.yml
roles/containerd/templates/config.toml.j2

Add parameter to containerd's role for setting a custom registry where to pull the pause (sandbox) image from. Default to SIGHUP's registry instead of upstream from now on to be aligned withe the rest of the on-premises installer.
Fixes #97 
This will trigger a restart of containerd's service when applied because we are changing the config by default.
A user could change the new default value to the old one (upstream: `k8s.gcr.io`) to avoid triggering the restart, even though I don't see the need to.
I suggest using the same version of the pause image that kubeadm expects at least until this gets sorted out by kubeadm and containerd. For previous versions of Kubernetes I left the version we had hardcoded, for the last version I aligned it with kubeadm, containerd will be restarted anyway …

feat(containerd): custom registry for pause (sandbox) image

---

README.md
docs/releases/v1.30.6.md

This branch will be used to consolidate the release of the new version of the installer.
I already tagged v1.30.6-rc.2 as a starting point, to be included on kfd.yaml

Release v1.30.6

---

roles/containerd/tasks/main.yml

AlmaLinux is similar to Rocky, a derivative of RHEL. My company is moving to Alma over Rocky, so I need this to install a new cluster.

containerd: Add AlmaLinux to supported distros

---

docs/releases/unreleased.md
roles/containerd/tasks/main.yml

Added support for AlmaLinux in Ansible roles. This change allows installing and configuring containerd on AlmaLinux as per Rocky Linux and other RHEL-based distributions.
Closes: [#546](https://github.com/sighupio/product-management/issues/546)
Added AlmaLinux to the list of supported distributions in the compatibility check. Now, the role will no longer fail on AlmaLinux distros.
None.
None.

feat: add AlmaLinux support

---

docs/releases/unreleased.md
roles/kube-node-common/defaults/main.yml
roles/kube-node-common/tasks/repo-Debian.yml

- **Force download and dearmoring of GPG keys** because, by default, if Ansible finds the file already exists it does not replace it
- **Add more robust repository string parsing** to replace the (optional) `signed-by` string provided by users with a static one. This is to avoid adding new input parameters, and it comes with the added bonus that we make a syntax check on the provided repo string input.
Fixes #110 
Fixes #100  
If a user previously downloaded the K8S APT repository's GPG key in a node (either by using this module or manually, it makes no difference), and that key has expired, subsequent runs of this installer fail.
This PR aims to force the download and replacement of the APT repository's GPG keys every time this installer is run.
See issue #110 for more info.
None
This PR …

Bugfix: resolve failing upgrades on Debian/Ubuntu on corner cases

---

docs/releases/unreleased.md
roles/containerd/defaults/main.yml
roles/kube-control-plane/defaults/main.yml
roles/kube-control-plane/tasks/main.yml
roles/kube-control-plane/tasks/upgrade.yml
roles/kube-control-plane/templates/kubeadm-upgrade-config.yml.j2
roles/kube-control-plane/templates/kubeadm.yml.j2
roles/kube-control-plane/templates/patches/kube-controller-manager0+json.json.j2
roles/kube-control-plane/templates/patches/kube-scheduler0+json.json.j2

Move setting the `bind-address` to the Node's IP  configuration from the ClusterConfiguration object to kubeadm patches.
Fixes #115 
The kubeadm ClusterConfiguration is used for configuration common to all the nodes, while specific node configuration must me done using patches, as per kubeadm documentation.
Since kubeadm 1.31, kubeadm does not use ClusterConfiguration for the upgrades and uses the configuration stored in the ConfigMap instead. With patches we make sure the node-specific config is always applied.
> [!NOTE]
> The patches append the `--bind-address` flag to the end of the containers command arguments, without checking if it is already defined.
> This is not an issue, if the flag has been defined more than once, the last one is taken into account.
> [!NOTE]
> All tests were …

fix(kube-control-plane): use patches for node specific configuration

---

roles/containerd/templates/config.toml.j2

This PR fixes the containerd configuration template to ensure both runtime configurations (runc and nvidia) are available not in an exclusive way and:
- Incudes `SystemdCgroup = true` under the section `[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]`.
- Ensures that the runc runtime is always configured independently of nvidia settings.
Closes: [#112](https://github.com/sighupio/fury-kubernetes-on-premises/issues/112)
See above.
None.
None.

fix(containerd): runtime missing cri plugin option for the nvidia container toolkit support

---

roles/haproxy/defaults/main.yml

This change extends HAProxy installation capabilities to AlmaLinux.

haproxy: Add AlmaLinux support to HAProxy package dictionary

---

examples/playbooks/56.upgrade-worker-nodes.yml
roles/kube-control-plane/handlers/kubelet_checks.yml
roles/kube-control-plane/handlers/main.yml
roles/kube-control-plane/tasks/reconfigure-kubelet.yml
roles/kube-control-plane/tasks/upgrade.yml
roles/kube-worker/handlers/kubelet_checks.yml
roles/kube-worker/handlers/main.yml
roles/kube-worker/tasks/reconfigure-kubelet.yml

As per title, with this PR we improve kubelet reconfiguration logic and:
- Add tasks for verifying kubelet status after applying patches
- Add logic to check if the kubelet service is active
- Ensure that failures are properly reported if kubelet doesn't work
None.
None.
None.

fix(roles): improve kubelet configuration logic during the upgrade

---

roles/kube-control-plane/tasks/upgrade.yml

Being that:
1. We dropped the bind-address configuration from the kubeadm configuration and we move it to kubeadm patches files.
3. kubeadm legacy (k8s < 1.30) does not support the UpgradeConfiguration object to specify the upgrade commands flags
We need to pass explicitly the `--patches` flag to the legacy `kubeadm upgrade` command
Without this fix, the kube-scheduler and kube-controller-manager pods will have 127.0.0.1 as bind address and host of the probes.
With this fix, the bind-address flag and probes host are properly set (patches are applied)

fix(kube-control-plane): apply patches in legacy kubeadm upgrade

---

roles/kube-node-common/tasks/repo-Debian.yml

Add Ansible version check for disclaimer blockinfile task, [that uses a parameter added in ansible 2.16](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html#parameter-append_newline).
Being that this task is not critical, we run it only if the version of Ansible is compatible, otherwise the task fails blocking the whole cluster creation / update process.
Fixes #130 
Tested:

fix(kube-node-common): run task if compatible

---

roles/kube-node-common/tasks/repo-Debian.yml

This PR addresses an issue with Debian machines where installations fail because the `gpg` executable is missing.
Closes #65 
See above.
None.
None.

fix: ensure gnupg package is present in Debian machines

---

docs/releases/unreleased.md
roles/containerd/templates/config.toml.j2

Don't configure a default mirror for docker.io so the user can set their own and won't go in conflict.
Fixes #113
We were including a mirror configuration for `docker.io` pointing to `registry-1.docker.io`, I presume because it was present in the sample configuration from upstream in the past.
This caused an isse when the user wanted to configure its own mirror for `docker.io` using the configuration options provided by the role, because the key was already in use.
Upstream does not include anymore the mirror pointing to `registry-1.docker.io` in the [sample configuration file](https://github.com/containerd/containerd/blob/v1.7.26/docs/man/containerd-config.toml.5.md#example), so I removed it.
None
We will need eventually need to switch to the new configuration format and migrate all the …

fix(containerd): don't configure default mirror for docker.io

---

docs/releases/v1.33.4.md
roles/containerd/defaults/main.yml
roles/containerd/templates/config.toml.j2

Expose the `device_ownership_from_security_context` parameter for containerd's configuration.
Expose the `device_ownership_from_security_context` parameter from containerd, while keeping the default `false` value.
In some cases, like when using KubeVirt, it is needed to have it enabled.
None
Tested with SD version v1.33.4-rc + the installer from this branch. 
This parameter still exists in contianerd v2, with the same name and default value but it changes location in the configuration file.

feat(containerd): expose device_ownership_from_security_context

---

docs/releases/v1.33.4.md
roles/containerd/defaults/main.yml
roles/containerd/tasks/nvidia.yml
roles/haproxy/defaults/main.yml
roles/haproxy/tasks/main.yml
roles/kube-node-common/defaults/main.yml
roles/kube-node-common/tasks/main.yml

Renamed repository management variables from `*_manage_repositories` to `*_self_managed_repositories` to clarify that `true` means user manages repos externally.
Relates: [sighupio/installer-on-premises/pull/141](https://github.com/sighupio/installer-on-premises/pull/141)
Renamed fields to eliminate ambiguity:
- `containerd_manage_repositories` to `containerd_self_managed_repositories`
- `haproxy_manage_repositories` to `haproxy_self_managed_repositories`
- `kubernetes_manage_repositories` to `kubernetes_self_managed_repositories`
None.
None.

refactor: refactor repository management variables
